export interface CambodiaPlaceVariant { code: string; en: string; km: string; variants: string[]; }

export const CAMBODIA_PLACE_VARIANTS: CambodiaPlaceVariant[] = [
  { code: "KH-12", en: "Phnom Penh", km: "ភ្នំពេញ", variants: ["phnom-penh", "phnompenh", "pp", "p.p.", "phnum penh", "phnum pénh", "pnom penh", "ភ្នំពេញ"] },
  { code: "KH-1", en: "Banteay Meanchey", km: "បន្ទាយមានជ័យ", variants: ["banteay meanchey", "banteay mean chey", "banteay meanchoay", "bmc", "bantey meanchey", "បន្ទាយមានជ័យ"] },
  { code: "KH-2", en: "Battambang", km: "បាត់ដំបង", variants: ["battambang", "batdambang", "bb", "btb", "bat dambang", "បាត់ដំបង"] },
  { code: "KH-3", en: "Kampong Cham", km: "កំពង់ចាម", variants: ["kampong cham", "kompong cham", "kpc", "kc", "កំពង់ចាម"] },
  { code: "KH-4", en: "Kampong Chhnang", km: "កំពង់ឆ្នាំង", variants: ["kampong chhnang", "kompong chhnang", "kg chhnang", "k. chhnang", "កំពង់ឆ្នាំង"] },
  { code: "KH-5", en: "Kampong Speu", km: "កំពង់ស្ពឺ", variants: ["kampong speu", "kompong speu", "kg speu", "កំពង់ស្ពឺ"] },
  { code: "KH-6", en: "Kampong Thom", km: "កំពង់ធំ", variants: ["kampong thom", "kompong thom", "kg thom", "កំពង់ធំ"] },
  { code: "KH-7", en: "Kampot", km: "កំពត", variants: ["kampot", "kompot", "kp", "កំពត"] },
  { code: "KH-8", en: "Kandal", km: "កណ្តាល", variants: ["kandal", "kândal", "kd", "កណ្តាល", "កណ្ដាល"] },
  { code: "KH-9", en: "Koh Kong", km: "កោះកុង", variants: ["koh kong", "kaoh kong", "kk", "កោះកុង"] },
  { code: "KH-10", en: "Kratié", km: "ក្រចេះ", variants: ["kratie", "kratié", "kracheh", "kt", "ក្រចេះ"] },
  { code: "KH-11", en: "Mondulkiri", km: "មណ្ឌលគិរី", variants: ["mondulkiri", "mondul kiri", "mondolkiri", "mdk", "mk", "មណ្ឌលគិរី"] },
  { code: "KH-22", en: "Oddar Meanchey", km: "ឧត្តរមានជ័យ", variants: ["oddar meanchey", "otdar meanchey", "oddar mean chey", "omc", "ឧត្តរមានជ័យ"] },
  { code: "KH-24", en: "Pailin", km: "ប៉ៃលិន", variants: ["pailin", "pl", "ប៉ៃលិន"] },
  { code: "KH-18", en: "Preah Sihanouk", km: "ព្រះសីហនុ", variants: ["preah sihanouk", "sihanoukville", "sihanouk ville", "shv", "kampong som", "kampong saom", "ព្រះសីហនុ"] },
  { code: "KH-13", en: "Preah Vihear", km: "ព្រះវិហារ", variants: ["preah vihear", "preah vihar", "pvh", "ព្រះវិហារ"] },
  { code: "KH-14", en: "Prey Veng", km: "ព្រៃវែង", variants: ["prey veng", "prey vung", "pv", "ព្រៃវែង"] },
  { code: "KH-15", en: "Pursat", km: "ពោធិ៍សាត់", variants: ["pursat", "pouthisat", "pousaat", "ps", "ពោធិ៍សាត់"] },
  { code: "KH-16", en: "Ratanakiri", km: "រតនគិរី", variants: ["ratanakiri", "ratanak kiri", "rotanokiri", "rtk", "rk", "រតនគិរី"] },
  { code: "KH-17", en: "Siem Reap", km: "សៀមរាប", variants: ["siem reap", "siemreap", "sr", "siem reab", "សៀមរាប"] },
  { code: "KH-19", en: "Stung Treng", km: "ស្ទឹងត្រែង", variants: ["stung treng", "stueng traeng", "stoeng treng", "st", "ស្ទឹងត្រែង"] },
  { code: "KH-20", en: "Svay Rieng", km: "ស្វាយរៀង", variants: ["svay rieng", "svayrieng", "svr", "ស្វាយរៀង"] },
  { code: "KH-21", en: "Takéo", km: "តាកែវ", variants: ["takeo", "takéo", "takev", "ta kaev", "tk", "តាកែវ"] },
  { code: "KH-25", en: "Tboung Khmum", km: "ត្បូងឃ្មុំ", variants: ["tboung khmum", "tbong khmum", "tboung khmom", "tk", "ត្បូងឃ្មុំ"] },
  { code: "KH-23", en: "Kep", km: "កែប", variants: ["kep", "keb", "កែប"] },
];
