export const LETTER_CATEGORIES = ["Requests", "Notices", "Invitations", "Confirmations", "Human resources", "Meetings", "Finance & procurement", "Education & community"] as const;
export type LetterCategory = (typeof LETTER_CATEGORIES)[number];
export type KhmerLetterTemplate = { id: string; label: string; labelEn: string; category: LetterCategory; subject: string; body: string };

type Seed = [id: string, label: string, labelEn: string, category: LetterCategory, subject: string, purpose: string];

function complete([id, label, labelEn, category, subject, purpose]: Seed): KhmerLetterTemplate {
  const openings: Record<LetterCategory, string> = {
    Requests: "យោងតាមតម្រូវការការងារ និងកម្មវត្ថុខាងលើ ខ្ញុំបាទ/នាងខ្ញុំ សូមគោរពស្នើសុំ",
    Notices: "សូមគោរពជម្រាបជូនថា អង្គភាពបានពិនិត្យ និងសម្រេចជូនដំណឹងអំពី",
    Invitations: "ខ្ញុំបាទ/នាងខ្ញុំ មានកិត្តិយសសូមគោរពអញ្ជើញ ឯកឧត្តម/លោកជំទាវ/លោក/លោកស្រី ចូលរួម",
    Confirmations: "លិខិតនេះបញ្ជាក់ថា អង្គភាពបានពិនិត្យឯកសារ និងព័ត៌មានពាក់ព័ន្ធនឹង",
    "Human resources": "យោងតាមបទបញ្ជាផ្ទៃក្នុង និងតម្រូវការគ្រប់គ្រងធនធានមនុស្ស អង្គភាពសូមជម្រាបអំពី",
    Meetings: "ដើម្បីធានាការសម្របសម្រួល និងការអនុវត្តការងារឱ្យមានប្រសិទ្ធភាព អង្គភាពសូមជម្រាបអំពី",
    "Finance & procurement": "យោងតាមនីតិវិធីហិរញ្ញវត្ថុ និងលទ្ធកម្មជាធរមាន អង្គភាពសូមគោរពជម្រាបអំពី",
    "Education & community": "ដើម្បីគាំទ្រការអប់រំ សេវាសាធារណៈ និងការចូលរួមរបស់សហគមន៍ អង្គភាពសូមជម្រាបអំពី",
  };
  return { id, label, labelEn, category, subject, body: `${openings[category]} ${purpose}។\n\nសូមលោកអ្នកពិនិត្យព័ត៌មាន ឯកសារភ្ជាប់ កាលបរិច្ឆេទ និងលក្ខខណ្ឌពាក់ព័ន្ធ ហើយផ្តល់កិច្ចសហការ ឬការឆ្លើយតបតាមសមត្ថកិច្ច។\n\nអាស្រ័យហេតុនេះ សូមមេត្តាជ្រាប និងចាត់ការតាមការគួរ។ សូមទទួលនូវការគោរពដ៏ខ្ពង់ខ្ពស់។` };
}

const SEEDS: Seed[] = [
  ["permission-request", "លិខិតស្នើសុំការអនុញ្ញាត", "Permission request", "Requests", "សំណើសុំការអនុញ្ញាត", "ការអនុញ្ញាតអនុវត្តសកម្មភាពដែលបានរៀបរាប់ក្នុងឯកសារភ្ជាប់"],
  ["leave-request", "លិខិតស្នើសុំច្បាប់ឈប់សម្រាក", "Leave request", "Requests", "សំណើសុំច្បាប់ឈប់សម្រាក", "ច្បាប់ឈប់សម្រាកតាមរយៈពេល និងមូលហេតុដែលបានបញ្ជាក់"],
  ["document-request", "លិខិតស្នើសុំឯកសារ", "Document request", "Requests", "សំណើសុំផ្តល់ឯកសារ", "ការផ្តល់ច្បាប់ចម្លងឯកសារ ឬព័ត៌មានដែលចាំបាច់សម្រាប់ការងារ"],
  ["support-request", "លិខិតស្នើសុំការគាំទ្រ", "Support request", "Requests", "សំណើសុំការគាំទ្រ", "ការគាំទ្រផ្នែកបច្ចេកទេស សម្ភារៈ ឬធនធានមនុស្ស"],
  ["budget-request", "លិខិតស្នើសុំថវិកា", "Budget request", "Requests", "សំណើសុំថវិកា", "ការអនុម័តថវិកាសម្រាប់សកម្មភាព និងចំណាយដែលបានគ្រោងទុក"],
  ["equipment-request", "លិខិតស្នើសុំសម្ភារៈ", "Equipment request", "Requests", "សំណើសុំសម្ភារៈបរិក្ខារ", "ការផ្តល់សម្ភារៈបរិក្ខារចាំបាច់សម្រាប់បំពេញភារកិច្ច"],
  ["training-request", "លិខិតស្នើសុំចូលរួមវគ្គបណ្តុះបណ្តាល", "Training request", "Requests", "សំណើសុំចូលរួមវគ្គបណ្តុះបណ្តាល", "ការអនុញ្ញាតឱ្យចូលរួមវគ្គបណ្តុះបណ្តាលដើម្បីពង្រឹងសមត្ថភាព"],
  ["transfer-request", "លិខិតស្នើសុំផ្ទេរកន្លែងការងារ", "Transfer request", "Requests", "សំណើសុំផ្ទេរកន្លែងការងារ", "ការពិចារណាផ្ទេរទីតាំង ឬអង្គភាពបំពេញការងារ"],
  ["meeting-request", "លិខិតស្នើសុំប្រជុំ", "Meeting request", "Requests", "សំណើសុំរៀបចំកិច្ចប្រជុំ", "ការរៀបចំកិច្ចប្រជុំដើម្បីពិភាក្សា និងសម្រេចលើបញ្ហាពាក់ព័ន្ធ"],
  ["extension-request", "លិខិតស្នើសុំពន្យារពេល", "Deadline extension request", "Requests", "សំណើសុំពន្យារពេល", "ការពន្យារកាលកំណត់អនុវត្ត ឬប្រគល់ការងារ"],
  ["data-request", "លិខិតស្នើសុំទិន្នន័យ", "Data request", "Requests", "សំណើសុំទិន្នន័យ", "ការផ្តល់ទិន្នន័យសម្រាប់រៀបចំរបាយការណ៍ និងវិភាគ"],
  ["cooperation-request", "លិខិតស្នើសុំកិច្ចសហការ", "Cooperation request", "Requests", "សំណើសុំកិច្ចសហការ", "ការសហការអនុវត្តសកម្មភាពរួម និងចែករំលែកធនធាន"],
  ["venue-request", "លិខិតស្នើសុំប្រើប្រាស់ទីកន្លែង", "Venue request", "Requests", "សំណើសុំប្រើប្រាស់ទីកន្លែង", "ការអនុញ្ញាតប្រើប្រាស់បន្ទប់ សាល ឬបរិវេណសម្រាប់កម្មវិធី"],
  ["vehicle-request", "លិខិតស្នើសុំប្រើប្រាស់យានយន្ត", "Vehicle request", "Requests", "សំណើសុំប្រើប្រាស់យានយន្ត", "ការរៀបចំយានយន្តសម្រាប់បេសកកម្ម ឬដឹកជញ្ជូន"],
  ["mission-request", "លិខិតស្នើសុំបេសកកម្ម", "Mission request", "Requests", "សំណើសុំចុះបេសកកម្ម", "ការអនុញ្ញាតចុះបេសកកម្មតាមគោលដៅ និងរយៈពេលដែលបានកំណត់"],

  ["policy-notice", "សេចក្តីជូនដំណឹងអំពីគោលការណ៍", "Policy notice", "Notices", "សេចក្តីជូនដំណឹងអំពីគោលការណ៍ថ្មី", "គោលការណ៍ថ្មី និងកាលបរិច្ឆេទចាប់ផ្តើមអនុវត្ត"],
  ["schedule-notice", "សេចក្តីជូនដំណឹងអំពីកាលវិភាគ", "Schedule notice", "Notices", "សេចក្តីជូនដំណឹងអំពីកាលវិភាគការងារ", "កាលវិភាគការងារ និងការបែងចែកភារកិច្ច"],
  ["closure-notice", "សេចក្តីជូនដំណឹងអំពីការផ្អាកសេវា", "Service closure notice", "Notices", "សេចក្តីជូនដំណឹងអំពីការផ្អាកសេវាបណ្ដោះអាសន្ន", "ការផ្អាកសេវាបណ្ដោះអាសន្ន និងពេលវេលាបើកដំណើរការឡើងវិញ"],
  ["maintenance-notice", "សេចក្តីជូនដំណឹងអំពីការថែទាំ", "Maintenance notice", "Notices", "សេចក្តីជូនដំណឹងអំពីការថែទាំប្រព័ន្ធ", "ការថែទាំប្រព័ន្ធ ឬសម្ភារៈ និងផលប៉ះពាល់ដែលអាចកើតមាន"],
  ["deadline-notice", "សេចក្តីជូនដំណឹងអំពីកាលកំណត់", "Deadline notice", "Notices", "រំលឹកកាលកំណត់ប្រគល់ឯកសារ", "កាលកំណត់ប្រគល់ឯកសារ និងលក្ខខណ្ឌទទួលយក"],
  ["procedure-notice", "សេចក្តីជូនដំណឹងអំពីនីតិវិធី", "Procedure notice", "Notices", "សេចក្តីជូនដំណឹងអំពីនីតិវិធីថ្មី", "នីតិវិធីថ្មីសម្រាប់ដាក់សំណើ ពិនិត្យ និងអនុម័ត"],
  ["safety-notice", "សេចក្តីជូនដំណឹងសុវត្ថិភាព", "Safety notice", "Notices", "សេចក្តីជូនដំណឹងអំពីសុវត្ថិភាព", "វិធានការសុវត្ថិភាព និងការឆ្លើយតបពេលមានហេតុការណ៍"],
  ["relocation-notice", "សេចក្តីជូនដំណឹងប្តូរទីតាំង", "Relocation notice", "Notices", "សេចក្តីជូនដំណឹងអំពីការប្តូរទីតាំង", "ការប្តូរទីតាំងការិយាល័យ ឬកន្លែងផ្តល់សេវា"],
  ["contact-notice", "សេចក្តីជូនដំណឹងប្តូរព័ត៌មានទំនាក់ទំនង", "Contact change notice", "Notices", "សេចក្តីជូនដំណឹងប្តូរព័ត៌មានទំនាក់ទំនង", "លេខទូរស័ព្ទ អ៊ីមែល ឬអាសយដ្ឋានទំនាក់ទំនងថ្មី"],
  ["event-notice", "សេចក្តីជូនដំណឹងអំពីកម្មវិធី", "Event notice", "Notices", "សេចក្តីជូនដំណឹងអំពីកម្មវិធី", "កម្មវិធីដែលនឹងរៀបចំ ពេលវេលា ទីកន្លែង និងអ្នកចូលរួម"],
  ["result-notice", "សេចក្តីជូនដំណឹងអំពីលទ្ធផល", "Result notice", "Notices", "សេចក្តីជូនដំណឹងអំពីលទ្ធផល", "លទ្ធផលនៃការពិនិត្យ វាយតម្លៃ ឬជ្រើសរើស"],
  ["compliance-notice", "សេចក្តីជូនដំណឹងអំពីការអនុលោម", "Compliance notice", "Notices", "សេចក្តីជូនដំណឹងអំពីការអនុលោមតាមបទប្បញ្ញត្តិ", "ការអនុវត្តបទប្បញ្ញត្តិ និងឯកសារត្រូវបំពេញ"],
  ["emergency-notice", "សេចក្តីជូនដំណឹងបន្ទាន់", "Emergency notice", "Notices", "សេចក្តីជូនដំណឹងបន្ទាន់", "ស្ថានភាពបន្ទាន់ វិធានការឆ្លើយតប និងចំណុចទំនាក់ទំនង"],
  ["holiday-notice", "សេចក្តីជូនដំណឹងថ្ងៃឈប់សម្រាក", "Holiday notice", "Notices", "សេចក្តីជូនដំណឹងអំពីថ្ងៃឈប់សម្រាក", "កាលបរិច្ឆេទឈប់សម្រាក និងការរៀបចំវេនការងារ"],
  ["appointment-notice", "សេចក្តីជូនដំណឹងតែងតាំង", "Appointment notice", "Notices", "សេចក្តីជូនដំណឹងអំពីការតែងតាំង", "ការតែងតាំងមន្ត្រី ឬអ្នកទទួលបន្ទុក និងវិសាលភាពភារកិច្ច"],
  ["meeting-invitation", "លិខិតអញ្ជើញចូលរួមប្រជុំ", "Meeting invitation", "Invitations", "អញ្ជើញចូលរួមកិច្ចប្រជុំ", "កិច្ចប្រជុំតាមរបៀបវារៈ ពេលវេលា និងទីកន្លែងដែលបានកំណត់"],
  ["workshop-invitation", "លិខិតអញ្ជើញចូលរួមសិក្ខាសាលា", "Workshop invitation", "Invitations", "អញ្ជើញចូលរួមសិក្ខាសាលា", "សិក្ខាសាលាផ្សព្វផ្សាយ និងពិភាក្សាលើប្រធានបទដែលបានបញ្ជាក់"],
  ["training-invitation", "លិខិតអញ្ជើញចូលរួមបណ្តុះបណ្តាល", "Training invitation", "Invitations", "អញ្ជើញចូលរួមវគ្គបណ្តុះបណ្តាល", "វគ្គបណ្តុះបណ្តាលពង្រឹងចំណេះដឹង និងជំនាញ"],
  ["ceremony-invitation", "លិខិតអញ្ជើញចូលរួមពិធី", "Ceremony invitation", "Invitations", "អញ្ជើញចូលរួមពិធីផ្លូវការ", "ពិធីផ្លូវការតាមកម្មវិធី និងពិធីការដែលបានរៀបចំ"],
  ["launch-invitation", "លិខិតអញ្ជើញសម្ពោធកម្មវិធី", "Launch invitation", "Invitations", "អញ្ជើញចូលរួមពិធីសម្ពោធ", "ពិធីសម្ពោធគម្រោង សេវា ឬសមិទ្ធផលថ្មី"],
  ["consultation-invitation", "លិខិតអញ្ជើញពិគ្រោះយោបល់", "Consultation invitation", "Invitations", "អញ្ជើញចូលរួមពិគ្រោះយោបល់", "វេទិកាពិគ្រោះយោបល់ និងផ្តល់មតិយោបល់លើសេចក្តីព្រាង"],
  ["interview-invitation", "លិខិតអញ្ជើញសម្ភាសន៍", "Interview invitation", "Invitations", "អញ្ជើញចូលរួមសម្ភាសន៍", "ការសម្ភាសន៍តាមពេលវេលា ទីកន្លែង និងឯកសារដែលត្រូវនាំមក"],
  ["inspection-invitation", "លិខិតអញ្ជើញចូលរួមចុះពិនិត្យ", "Inspection invitation", "Invitations", "អញ្ជើញចូលរួមចុះពិនិត្យ", "ការចុះពិនិត្យទីតាំង ការងារ ឬសម្ភារៈជាក់ស្តែង"],
  ["celebration-invitation", "លិខិតអញ្ជើញកម្មវិធីអបអរសាទរ", "Celebration invitation", "Invitations", "អញ្ជើញចូលរួមកម្មវិធីអបអរសាទរ", "កម្មវិធីអបអរសាទរសមិទ្ធផល ឬឱកាសសំខាន់"],
  ["stakeholder-invitation", "លិខិតអញ្ជើញភាគីពាក់ព័ន្ធ", "Stakeholder invitation", "Invitations", "អញ្ជើញភាគីពាក់ព័ន្ធចូលរួម", "កិច្ចពិភាក្សារួមជាមួយភាគីពាក់ព័ន្ធដើម្បីសម្របសម្រួលការងារ"],

  ["employment-confirmation", "លិខិតបញ្ជាក់ការងារ", "Employment confirmation", "Confirmations", "ការបញ្ជាក់ការងារ", "ស្ថានភាពបំពេញការងារ តួនាទី និងរយៈពេលបម្រើការងារ"],
  ["salary-confirmation", "លិខិតបញ្ជាក់ប្រាក់ខែ", "Salary confirmation", "Confirmations", "ការបញ្ជាក់ប្រាក់ខែ", "ប្រាក់ខែ និងអត្ថប្រយោជន៍តាមកំណត់ត្រារបស់អង្គភាព"],
  ["residence-confirmation", "លិខិតបញ្ជាក់ទីលំនៅ", "Residence confirmation", "Confirmations", "ការបញ្ជាក់ទីលំនៅ", "ទីលំនៅរបស់សាមីជនតាមឯកសារ និងការបញ្ជាក់ដែលបានទទួល"],
  ["service-confirmation", "លិខិតបញ្ជាក់ការផ្តល់សេវា", "Service confirmation", "Confirmations", "ការបញ្ជាក់ការផ្តល់សេវា", "សេវាដែលបានផ្តល់ រយៈពេល និងលទ្ធផលសម្រេច"],
  ["participation-confirmation", "លិខិតបញ្ជាក់ការចូលរួម", "Participation confirmation", "Confirmations", "ការបញ្ជាក់ការចូលរួម", "ការចូលរួមកម្មវិធី កិច្ចប្រជុំ ឬវគ្គបណ្តុះបណ្តាល"],
  ["completion-confirmation", "លិខិតបញ្ជាក់ការបញ្ចប់ការងារ", "Completion confirmation", "Confirmations", "ការបញ្ជាក់ការបញ្ចប់ការងារ", "ការបញ្ចប់ភារកិច្ច ឬសកម្មភាពតាមវិសាលភាពដែលបានកំណត់"],
  ["receipt-confirmation", "លិខិតបញ្ជាក់ទទួលឯកសារ", "Document receipt confirmation", "Confirmations", "ការបញ្ជាក់ទទួលឯកសារ", "ការទទួលឯកសារ ចំនួនច្បាប់ និងកាលបរិច្ឆេទទទួល"],
  ["identity-confirmation", "លិខិតបញ្ជាក់អត្តសញ្ញាណ", "Identity confirmation", "Confirmations", "ការបញ្ជាក់អត្តសញ្ញាណ", "អត្តសញ្ញាណរបស់សាមីជនតាមឯកសារដែលបានពិនិត្យ"],
  ["internship-confirmation", "លិខិតបញ្ជាក់កម្មសិក្សា", "Internship confirmation", "Confirmations", "ការបញ្ជាក់កម្មសិក្សា", "រយៈពេលកម្មសិក្សា ផ្នែកការងារ និងការបំពេញភារកិច្ច"],
  ["volunteer-confirmation", "លិខិតបញ្ជាក់ការងារស្ម័គ្រចិត្ត", "Volunteer confirmation", "Confirmations", "ការបញ្ជាក់ការងារស្ម័គ្រចិត្ត", "ការចូលរួមការងារស្ម័គ្រចិត្ត និងរយៈពេលបំពេញសកម្មភាព"],
  ["payment-confirmation", "លិខិតបញ្ជាក់ការទូទាត់", "Payment confirmation", "Confirmations", "ការបញ្ជាក់ការទូទាត់", "ការទូទាត់តាមវិក្កយបត្រ ចំនួនទឹកប្រាក់ និងកាលបរិច្ឆេទ"],
  ["ownership-confirmation", "លិខិតបញ្ជាក់ការកាន់កាប់សម្ភារៈ", "Asset custody confirmation", "Confirmations", "ការបញ្ជាក់ការកាន់កាប់សម្ភារៈ", "សម្ភារៈដែលបានប្រគល់ជូនសម្រាប់ប្រើប្រាស់ និងថែរក្សា"],
  ["good-standing-confirmation", "លិខិតបញ្ជាក់អាកប្បកិរិយា", "Good standing confirmation", "Confirmations", "ការបញ្ជាក់អាកប្បកិរិយា និងវិន័យ", "កំណត់ត្រាអាកប្បកិរិយា វិន័យ និងការអនុវត្តបទបញ្ជា"],
  ["project-confirmation", "លិខិតបញ្ជាក់សកម្មភាពគម្រោង", "Project activity confirmation", "Confirmations", "ការបញ្ជាក់សកម្មភាពគម្រោង", "សកម្មភាពគម្រោង ទីតាំង រយៈពេល និងអ្នកទទួលខុសត្រូវ"],
  ["information-confirmation", "លិខិតបញ្ជាក់ព័ត៌មានទូទៅ", "General information confirmation", "Confirmations", "ការបញ្ជាក់ព័ត៌មាន", "ព័ត៌មានដែលមានក្នុងកំណត់ត្រា និងឯកសាររបស់អង្គភាព"],
  ["appointment-letter", "លិខិតតែងតាំង", "Appointment letter", "Human resources", "ការតែងតាំងមុខតំណែង", "ការតែងតាំងបុគ្គលិកក្នុងមុខតំណែង និងភារកិច្ចដែលបានកំណត់"],
  ["assignment-letter", "លិខិតប្រគល់ភារកិច្ច", "Assignment letter", "Human resources", "ការប្រគល់ភារកិច្ច", "ការប្រគល់ភារកិច្ចជាក់លាក់ រយៈពេល និងខ្សែសង្វាក់ទទួលខុសត្រូវ"],
  ["promotion-letter", "លិខិតដំឡើងតួនាទី", "Promotion letter", "Human resources", "ការដំឡើងតួនាទី", "ការដំឡើងតួនាទី និងលក្ខខណ្ឌការងារថ្មី"],
  ["transfer-letter", "លិខិតផ្ទេរបុគ្គលិក", "Staff transfer letter", "Human resources", "ការផ្ទេរបុគ្គលិក", "ការផ្ទេរទៅអង្គភាព ឬទីតាំងថ្មី និងកាលបរិច្ឆេទមានប្រសិទ្ធភាព"],
  ["probation-letter", "លិខិតបញ្ជាក់សាកល្បងការងារ", "Probation letter", "Human resources", "ការសាកល្បងការងារ", "រយៈពេលសាកល្បងការងារ លក្ខខណ្ឌ និងការវាយតម្លៃ"],
  ["contract-renewal", "លិខិតបន្តកិច្ចសន្យា", "Contract renewal letter", "Human resources", "ការបន្តកិច្ចសន្យាការងារ", "ការបន្តកិច្ចសន្យា រយៈពេល និងលក្ខខណ្ឌដែលបានព្រមព្រៀង"],
  ["warning-letter", "លិខិតព្រមាន", "Warning letter", "Human resources", "លិខិតព្រមានអំពីការអនុវត្តការងារ", "ករណីមិនអនុលោម ការកែលម្អដែលត្រូវការ និងកាលកំណត់តាមដាន"],
  ["discipline-letter", "លិខិតស្តីបន្ទោស", "Disciplinary letter", "Human resources", "ការអនុវត្តវិធានវិន័យ", "មូលហេតុ វិធានវិន័យ និងសិទ្ធិឆ្លើយតបរបស់បុគ្គលិក"],
  ["resignation-acceptance", "លិខិតទទួលការលាលែង", "Resignation acceptance", "Human resources", "ការទទួលយកការលាលែងពីការងារ", "ការទទួលយកលិខិតលាលែង ថ្ងៃការងារចុងក្រោយ និងការប្រគល់ការងារ"],
  ["termination-letter", "លិខិតបញ្ចប់កិច្ចសន្យា", "Contract termination letter", "Human resources", "ការបញ្ចប់កិច្ចសន្យាការងារ", "មូលដ្ឋាន កាលបរិច្ឆេទ និងនីតិវិធីបញ្ចប់កិច្ចសន្យា"],
  ["commendation-letter", "លិខិតសរសើរ", "Commendation letter", "Human resources", "ការកោតសរសើរលទ្ធផលការងារ", "ស្នាដៃ ការខិតខំប្រឹងប្រែង និងការរួមចំណែករបស់បុគ្គលិក"],
  ["recommendation-letter", "លិខិតអនុសាសន៍", "Recommendation letter", "Human resources", "លិខិតអនុសាសន៍", "សមត្ថភាព បទពិសោធន៍ និងគុណសម្បត្តិរបស់សាមីជន"],
  ["return-to-work", "លិខិតជូនដំណឹងចូលបម្រើការងារវិញ", "Return-to-work letter", "Human resources", "ការចូលបម្រើការងារវិញ", "កាលបរិច្ឆេទ និងការរៀបចំចូលបម្រើការងារវិញបន្ទាប់ពីឈប់សម្រាក"],
  ["overtime-approval", "លិខិតអនុម័តការងារបន្ថែមម៉ោង", "Overtime approval", "Human resources", "ការអនុម័តការងារបន្ថែមម៉ោង", "ពេលវេលា មូលហេតុ និងអ្នកទទួលខុសត្រូវលើការងារបន្ថែមម៉ោង"],
  ["performance-review", "លិខិតជូនដំណឹងវាយតម្លៃការងារ", "Performance review notice", "Human resources", "លទ្ធផលវាយតម្លៃការងារ", "លទ្ធផលវាយតម្លៃ ចំណុចខ្លាំង និងផែនការកែលម្អ"],

  ["meeting-agenda", "លិខិតបញ្ជូនរបៀបវារៈប្រជុំ", "Meeting agenda letter", "Meetings", "ការបញ្ជូនរបៀបវារៈកិច្ចប្រជុំ", "របៀបវារៈ ឯកសារត្រៀម និងពេលវេលាកិច្ចប្រជុំ"],
  ["meeting-minutes", "លិខិតបញ្ជូនកំណត់ហេតុប្រជុំ", "Meeting minutes letter", "Meetings", "ការបញ្ជូនកំណត់ហេតុកិច្ចប្រជុំ", "សេចក្តីសម្រេច អ្នកទទួលខុសត្រូវ និងកាលកំណត់ពីកិច្ចប្រជុំ"],
  ["meeting-postponement", "លិខិតពន្យារកិច្ចប្រជុំ", "Meeting postponement", "Meetings", "ការពន្យារកិច្ចប្រជុំ", "ការផ្លាស់ប្តូរកាលបរិច្ឆេទ ពេលវេលា ឬទីកន្លែងប្រជុំ"],
  ["meeting-cancellation", "លិខិតលុបកិច្ចប្រជុំ", "Meeting cancellation", "Meetings", "ការលុបកិច្ចប្រជុំ", "ការលុបកិច្ចប្រជុំ និងការជូនដំណឹងអំពីជំហានបន្ទាប់"],
  ["decision-letter", "លិខិតជូនដំណឹងសេចក្តីសម្រេច", "Decision letter", "Meetings", "សេចក្តីសម្រេចរបស់កិច្ចប្រជុំ", "សេចក្តីសម្រេចដែលបានអនុម័ត និងការអនុវត្តបន្ត"],
  ["action-follow-up", "លិខិតតាមដានសកម្មភាព", "Action follow-up letter", "Meetings", "ការតាមដានសកម្មភាពក្រោយកិច្ចប្រជុំ", "វឌ្ឍនភាពការងារ បញ្ហាប្រឈម និងកាលកំណត់សកម្មភាព"],
  ["nomination-letter", "លិខិតចាត់តាំងតំណាងចូលរួមប្រជុំ", "Meeting representative nomination", "Meetings", "ការចាត់តាំងតំណាងចូលរួមកិច្ចប្រជុំ", "ការចាត់តាំងតំណាង សិទ្ធិ និងភារកិច្ចក្នុងកិច្ចប្រជុំ"],
  ["consultation-summary", "លិខិតសង្ខេបពិគ្រោះយោបល់", "Consultation summary", "Meetings", "សេចក្តីសង្ខេបកិច្ចពិគ្រោះយោបល់", "មតិយោបល់សំខាន់ៗ ចំណុចឯកភាព និងចំណុចត្រូវពិភាក្សាបន្ត"],
  ["coordination-letter", "លិខិតសម្របសម្រួលកិច្ចប្រជុំ", "Meeting coordination letter", "Meetings", "ការសម្របសម្រួលកិច្ចប្រជុំ", "ការរៀបចំទីកន្លែង ឯកសារ បច្ចេកទេស និងអ្នកចូលរួម"],
  ["quorum-notice", "លិខិតរំលឹកសមាជិកប្រជុំ", "Quorum reminder", "Meetings", "ការរំលឹកសមាជិកចូលរួមកិច្ចប្រជុំ", "វត្តមានសមាជិក អង្គប្រជុំ និងការបញ្ជាក់ចូលរួម"],
  ["quotation-request", "លិខិតស្នើសុំសម្រង់តម្លៃ", "Request for quotation", "Finance & procurement", "សំណើសុំសម្រង់តម្លៃ", "ការផ្តល់សម្រង់តម្លៃ លក្ខណៈបច្ចេកទេស និងលក្ខខណ្ឌផ្គត់ផ្គង់"],
  ["purchase-request", "លិខិតស្នើសុំទិញ", "Purchase request", "Finance & procurement", "សំណើសុំទិញទំនិញ ឬសេវា", "ការទិញទំនិញ ឬសេវាតាមបរិមាណ និងលក្ខណៈបច្ចេកទេស"],
  ["purchase-order", "លិខិតបញ្ជាទិញ", "Purchase order letter", "Finance & procurement", "ការបញ្ជាទិញទំនិញ ឬសេវា", "ការបញ្ជាទិញ តម្លៃ ពេលប្រគល់ និងលក្ខខណ្ឌទូទាត់"],
  ["payment-request", "លិខិតស្នើសុំទូទាត់", "Payment request", "Finance & procurement", "សំណើសុំទូទាត់", "ការទូទាត់តាមកិច្ចសន្យា វិក្កយបត្រ និងភស្តុតាងទទួលទំនិញ"],
  ["advance-request", "លិខិតស្នើសុំបុរេប្រទាន", "Advance request", "Finance & procurement", "សំណើសុំបុរេប្រទាន", "ប្រាក់បុរេប្រទានសម្រាប់សកម្មភាព និងផែនការទូទាត់បញ្ចប់"],
  ["expense-settlement", "លិខិតទូទាត់បញ្ចប់បុរេប្រទាន", "Expense settlement", "Finance & procurement", "ការទូទាត់បញ្ចប់បុរេប្រទាន", "ចំណាយជាក់ស្តែង បង្កាន់ដៃ និងសមតុល្យត្រូវសង ឬទទួល"],
  ["budget-reallocation", "លិខិតស្នើសុំផ្ទេរថវិកា", "Budget reallocation request", "Finance & procurement", "សំណើសុំផ្ទេរថវិកា", "ការផ្ទេរថវិការវាងបន្ទាត់ចំណាយដោយមានមូលហេតុ និងផលប៉ះពាល់"],
  ["delivery-acceptance", "លិខិតទទួលយកការប្រគល់", "Delivery acceptance letter", "Finance & procurement", "ការទទួលយកទំនិញ ឬសេវា", "ការត្រួតពិនិត្យ និងទទួលយកការប្រគល់តាមកិច្ចសន្យា"],
  ["invoice-dispute", "លិខិតជំទាស់វិក្កយបត្រ", "Invoice dispute letter", "Finance & procurement", "ការស្នើកែតម្រូវវិក្កយបត្រ", "ចំណុចមិនត្រឹមត្រូវក្នុងវិក្កយបត្រ និងឯកសារគាំទ្រការកែតម្រូវ"],
  ["contract-amendment", "លិខិតស្នើកែប្រែកិច្ចសន្យា", "Contract amendment request", "Finance & procurement", "សំណើកែប្រែកិច្ចសន្យា", "ការកែប្រែវិសាលភាព តម្លៃ កាលកំណត់ ឬលក្ខខណ្ឌកិច្ចសន្យា"],
  ["student-enrollment", "លិខិតបញ្ជាក់ការចុះឈ្មោះសិក្សា", "Student enrollment letter", "Education & community", "ការបញ្ជាក់ការចុះឈ្មោះសិក្សា", "ការចុះឈ្មោះ វគ្គសិក្សា ថ្នាក់ និងឆ្នាំសិក្សារបស់សិស្ស"],
  ["scholarship-request", "លិខិតស្នើសុំអាហារូបករណ៍", "Scholarship request", "Education & community", "សំណើសុំអាហារូបករណ៍", "ការគាំទ្រថ្លៃសិក្សា និងលក្ខខណ្ឌអាហារូបករណ៍"],
  ["school-transfer", "លិខិតស្នើសុំផ្ទេរសាលា", "School transfer request", "Education & community", "សំណើសុំផ្ទេរការសិក្សា", "ការផ្ទេរសិស្សទៅគ្រឹះស្ថានថ្មី និងការបញ្ជូនកំណត់ត្រាសិក្សា"],
  ["parent-invitation", "លិខិតអញ្ជើញមាតាបិតា", "Parent invitation", "Education & community", "អញ្ជើញមាតាបិតា ឬអាណាព្យាបាល", "កិច្ចប្រជុំពិភាក្សាអំពីការសិក្សា វិន័យ និងសុខុមាលភាពសិស្ស"],
  ["community-meeting", "លិខិតអញ្ជើញប្រជុំសហគមន៍", "Community meeting invitation", "Education & community", "អញ្ជើញចូលរួមប្រជុំសហគមន៍", "កិច្ចប្រជុំសហគមន៍ដើម្បីពិភាក្សាតម្រូវការ ផែនការ និងការចូលរួម"],
  ["public-consultation", "លិខិតអញ្ជើញពិគ្រោះយោបល់សាធារណៈ", "Public consultation invitation", "Education & community", "អញ្ជើញចូលរួមពិគ្រោះយោបល់សាធារណៈ", "ការប្រមូលមតិសាធារណៈលើគម្រោង ឬផែនការអភិវឌ្ឍន៍"],
  ["donation-request", "លិខិតស្នើសុំឧបត្ថម្ភ", "Donation request", "Education & community", "សំណើសុំការឧបត្ថម្ភ", "ការឧបត្ថម្ភសម្ភារៈ ថវិកា ឬសេវាសម្រាប់សកម្មភាពសង្គម"],
  ["volunteer-invitation", "លិខិតអញ្ជើញអ្នកស្ម័គ្រចិត្ត", "Volunteer invitation", "Education & community", "អញ្ជើញចូលរួមការងារស្ម័គ្រចិត្ត", "សកម្មភាពស្ម័គ្រចិត្ត ភារកិច្ច ពេលវេលា និងវិធានសុវត្ថិភាព"],
  ["awareness-campaign", "លិខិតជូនដំណឹងយុទ្ធនាការផ្សព្វផ្សាយ", "Awareness campaign notice", "Education & community", "សេចក្តីជូនដំណឹងអំពីយុទ្ធនាការផ្សព្វផ្សាយ", "យុទ្ធនាការអប់រំសាធារណៈ គោលដៅ និងមធ្យោបាយចូលរួម"],
  ["community-thanks", "លិខិតថ្លែងអំណរគុណសហគមន៍", "Community appreciation letter", "Education & community", "ការថ្លែងអំណរគុណចំពោះសហគមន៍", "ការចូលរួម និងការគាំទ្ររបស់សហគមន៍ចំពោះសកម្មភាពរួម"],
];

export const KHMER_LETTER_TEMPLATES = SEEDS.map(complete);

if (KHMER_LETTER_TEMPLATES.length !== 100 || new Set(KHMER_LETTER_TEMPLATES.map((template) => template.id)).size !== 100) {
  throw new Error("Administrative letter template catalog must contain exactly 100 unique templates");
}