const EXACT: Record<string, string> = {
  "Background Remover": "ឧបករណ៍លុបផ្ទៃខាងក្រោយ", "Image Upscaler": "ឧបករណ៍ពង្រីករូបភាព", "Image Resizer & Compressor": "ប្តូរទំហំ និងបង្រួមរូបភាព", "Image Editor": "កម្មវិធីកែរូបភាព",
  "JSON Formatter": "រៀបចំទម្រង់ JSON", "Base64 Encode / Decode": "អ៊ិនកូដ / ឌីកូដ Base64", "URL Encode / Decode": "អ៊ិនកូដ / ឌីកូដ URL", "UUID Generator": "បង្កើត UUID", "Hash Generator": "បង្កើត Hash",
  "Khmer ⟷ Arabic Digits": "លេខខ្មែរ ⟷ លេខអារ៉ាប់", "Khmer Unicode Inspector": "ត្រួតពិនិត្យយូនីកូដខ្មែរ", "Khmer Grapheme Counter": "រាប់តួអក្សរខ្មែរ", "Riel Currency Formatter": "រៀបចំទម្រង់ប្រាក់រៀល",
  "Cambodia Province Lookup": "ស្វែងរកខេត្តកម្ពុជា", "Nearest Province Finder": "ស្វែងរកខេត្តដែលនៅជិតបំផុត", "Cambodia Provinces Reference": "បញ្ជីខេត្ត-រាជធានីកម្ពុជា",
  "Password Generator": "បង្កើតពាក្យសម្ងាត់", "Password Strength Estimator": "វាយតម្លៃកម្រិតពាក្យសម្ងាត់", "QR Code Generator": "បង្កើតកូដ QR", "QR Code Decoder": "អានកូដ QR",
};
Object.assign(EXACT, {
  // Development
  "JWT Decoder": "ឧបករណ៍ឌិកូដ JWT", "Regex Tester": "ឧបករណ៍សាកល្បង Regex", "Markdown Previewer": "មើល Markdown ជាមុន", "Text Diff Checker": "ប្រៀបធៀបភាពខុសគ្នានៃអត្ថបទ",   "Word & Character Counter": "រាប់ពាក្យ និងតួអក្សរ", "Placeholder Text Generator": "បង្កើតអត្ថបទគំរូ", "TSX Portal": "TSX Portal", "Color Converter": "បម្លែងទម្រង់ពណ៌", "Unix Timestamp Converter": "បម្លែងត្រាពេលវេលា Unix", "Case Converter": "បម្លែងទម្រង់អក្សរ", "Slug Generator": "បង្កើត Slug",
  "CSV → JSON": "បម្លែង CSV → JSON", "Cron Expression Explainer": "ពន្យល់កន្សោម Cron", "String Escape / Unescape": "Escape / Unescape ខ្សែអក្សរ", "CSV → Markdown Table": "បម្លែង CSV → តារាង Markdown", "GitHub Repo File Browser": "រុករកឯកសារឃ្លាំង GitHub", "Article / HTML Content Extractor": "ដកស្រង់ខ្លឹមសារអត្ថបទ / HTML",
  // Khmer and Cambodia
  "Buddhist Era Year Converter": "បម្លែងឆ្នាំពុទ្ធសករាជ", "12-Year Zodiac Cycle": "វដ្តឆ្នាំសត្វទាំង ១២", "Khmer Date Formatter": "រៀបចំទម្រង់កាលបរិច្ឆេទខ្មែរ", "Consonant Series Classifier": "ចាត់ថ្នាក់ស៊េរីព្យញ្ជនៈ", "Khmer Number Spell-out": "សរសេរលេខជាពាក្យខ្មែរ", "Phone Number Formatter": "រៀបចំទម្រង់លេខទូរសព្ទ", "National ID Shape Checker": "ពិនិត្យទម្រង់អត្តសញ្ញាណប័ណ្ណ", "Khmer Romanization": "បម្លែងអក្សរខ្មែរជាអក្សរឡាតាំង", "Soft Line-break Helper": "ជំនួយបំបែកបន្ទាត់ទន់", "Khmer Web Font Preview": "មើលពុម្ពអក្សរខ្មែរលើវេបជាមុន",
  "Riel ⟷ USD Converter": "បម្លែងប្រាក់រៀល ⟷ ដុល្លារ", "Dependent Vowel Reference": "តារាងស្រៈនិស្ស័យ", "Khmer Punctuation Reference": "តារាងសញ្ញាវណ្ណយុត្តិខ្មែរ", "Khmer Ordinal Number Formatter": "រៀបចំទម្រង់លេខលំដាប់ខ្មែរ", "Khmer Digital Terminology": "វាក្យស័ព្ទឌីជីថលខ្មែរ", "Khmer Language Resources": "ធនធានភាសាខ្មែរ", "Khmer Words → Number": "បម្លែងពាក្យលេខខ្មែរ → លេខ", "Khmer Syllable Splitter": "បំបែកព្យាង្គខ្មែរ", "Khmer Name Generator": "បង្កើតឈ្មោះខ្មែរ", "Cambodia Vehicle Plate Format Checker": "ពិនិត្យទម្រង់ស្លាកលេខយានយន្តកម្ពុជា",
  "Khmer Lunar Day": "ថ្ងៃចន្ទគតិខ្មែរ", "Khmer Full Lunar Date": "កាលបរិច្ឆេទចន្ទគតិខ្មែរពេញលេញ", "Khmer NLP & Speech Model Directory": "បញ្ជីម៉ូដែល NLP និងសំឡេងខ្មែរ", "Cambodia Open-Source Project Directory": "បញ្ជីគម្រោងកូដចំហកម្ពុជា", "Construction & Water Resources Glossary": "សទ្ទានុក្រមសំណង់ និងធនធានទឹក", "Khmer Collation Sorter": "តម្រៀបអក្សរតាមលំដាប់ខ្មែរ", "Khmer → URL Slug Generator": "បង្កើត URL Slug ពីអក្សរខ្មែរ", "Khmer Pronoun & Register Reference": "តារាងសព្វនាម និងកម្រិតភាសាខ្មែរ", "Khmer Line-Wrap CSS Fix": "កែបញ្ហាបំបែកបន្ទាត់ខ្មែរដោយ CSS", "Khmer Placeholder Text Generator": "បង្កើតអត្ថបទគំរូខ្មែរ",
  "Cambodia Postal Code Finder": "ស្វែងរកលេខកូដប្រៃសណីយ៍កម្ពុជា", "Cambodia Administrative Hierarchy": "ឋានានុក្រមរដ្ឋបាលកម្ពុជា", "Cambodia Government Institution Directory": "បញ្ជីស្ថាប័នរាជរដ្ឋាភិបាលកម្ពុជា", "Cambodia Government Plate Lookup": "ស្វែងរកស្លាកលេខរដ្ឋកម្ពុជា", "Khmer Unicode Normalizer": "សម្អាតយូនីកូដខ្មែរ", "Khmer Sentence Segmenter": "បំបែកប្រយោគខ្មែរ", "Cambodia Administrative Code Decoder": "អានលេខកូដរដ្ឋបាលកម្ពុជា", "Cambodia Bilingual Address Formatter": "រៀបចំអាសយដ្ឋានកម្ពុជាពីរភាសា", "Cambodia Government Plate Parser": "វិភាគស្លាកលេខរដ្ឋកម្ពុជា", "Cambodia EV Charging Station Finder": "ស្វែងរកស្ថានីយសាករថយន្តអគ្គិសនីនៅកម្ពុជា",
  // Geospatial
  "Decimal Degrees ⟷ DMS": "ដឺក្រេទសភាគ ⟷ ដឺក្រេ-នាទី-វិនាទី", "Haversine Distance": "គណនាចម្ងាយ Haversine", "Bounding Box Calculator": "គណនាប្រអប់ព្រំដែន", "Midpoint Calculator": "គណនាចំណុចកណ្ដាល", "Bearing / Azimuth Calculator": "គណនាទិសដៅ / អាស៊ីមុត", "Destination Point Calculator": "គណនាចំណុចគោលដៅ", "Polygon Area Calculator": "គណនាផ្ទៃក្រឡាពហុកោណ", "Geohash Encoder / Decoder": "អ៊ិនកូដ / ឌិកូដ Geohash", "Lat/Lng → UTM": "បម្លែងរយៈទទឹង/បណ្ដោយ → UTM", "GeoJSON Formatter & Validator": "រៀបចំ និងផ្ទៀងផ្ទាត់ GeoJSON",
  "Coordinate Format Cleaner": "សម្អាតទម្រង់កូអរដោនេ", "Area Unit Converter": "បម្លែងឯកតាផ្ទៃក្រឡា", "Map Scale Calculator": "គណនាមាត្រដ្ឋានផែនទី", "Slope / Grade Calculator": "គណនាជម្រាល / កម្រិត", "Cambodia Province Lookup": "ស្វែងរកខេត្តកម្ពុជា", "KML Placemark Inspector": "ពិនិត្យទីតាំងសម្គាល់ KML", "GPS Coordinate Validator": "ផ្ទៀងផ្ទាត់កូអរដោនេ GPS", "Speed / Distance / Time Calculator": "គណនាល្បឿន / ចម្ងាយ / ពេលវេលា", "Nearest Province Finder": "ស្វែងរកខេត្តដែលនៅជិតបំផុត",
  // Text
  "Sample Paragraph Generator": "បង្កើតកថាខណ្ឌគំរូ", "Text Reverse": "បញ្ច្រាសអត្ថបទ", "Palindrome Checker": "ពិនិត្យពាក្យបញ្ច្រាស", "Character Frequency Counter": "រាប់ប្រេកង់តួអក្សរ", "Line Sorter": "តម្រៀបបន្ទាត់", "Duplicate Line Remover": "លុបបន្ទាត់ស្ទួន", "Text Truncator": "កាត់អត្ថបទឱ្យខ្លី", "Find & Replace": "ស្វែងរក និងជំនួស", "Text ⟷ Binary": "អត្ថបទ ⟷ លេខគោលពីរ", "Text ⟷ Morse Code": "អត្ថបទ ⟷ កូដ Morse",
  "Acronym Generator": "បង្កើតពាក្យកាត់", "Random String Generator": "បង្កើតខ្សែអក្សរចៃដន្យ", "Text Statistics": "ស្ថិតិអត្ថបទ", "Whitespace / Line Cleaner": "សម្អាតចន្លោះ / បន្ទាត់", "Title Case Converter": "បម្លែងអក្សរធំតាមចំណងជើង", "Text to Columns Splitter": "បំបែកអត្ថបទជាជួរឈរ", "Anagram Checker": "ពិនិត្យអាណាក្រាម", "Text Line Numberer": "ដាក់លេខរៀងបន្ទាត់អត្ថបទ",
  // Math
  "Percentage Calculator": "គណនាភាគរយ", "Number Base Converter": "បម្លែងគោលលេខ", "GCD & LCM Calculator": "គណនា GCD និង LCM", "Prime Number Checker & Factorizer": "ពិនិត្យ និងបំបែកកត្តាចំនួនបឋម", "Fibonacci Sequence Generator": "បង្កើតលំដាប់ Fibonacci", "Quadratic Equation Solver": "ដោះស្រាយសមីការដឺក្រេទីពីរ", "Mean / Median / Mode / StdDev Calculator": "គណនាមធ្យម មេដ្យាន ម៉ូដ និងគម្លាតស្តង់ដារ", "Matrix Determinant": "គណនាដេតេមីណង់ម៉ាទ្រីស", "Length / Weight / Volume Unit Converter": "បម្លែងឯកតាប្រវែង / ទម្ងន់ / មាឌ", "Temperature Converter": "បម្លែងសីតុណ្ហភាព",
  "Random Number Generator": "បង្កើតលេខចៃដន្យ", "Ratio Simplifier": "សម្រួលសមាមាត្រ", "Roman Numeral Converter": "បម្លែងលេខរ៉ូម៉ាំង", "Right Triangle Solver": "ដោះស្រាយត្រីកោណកែង", "Compound Interest Calculator": "គណនាការប្រាក់សមាស", "Tip & Bill Split Calculator": "គណនាប្រាក់ធីប និងចែកវិក្កយបត្រ", "LaTeX Formula Renderer": "បង្ហាញរូបមន្ត LaTeX",
  // Network
  "CIDR / Subnet Calculator": "គណនា CIDR / Subnet", "IPv4 Address Parser": "វិភាគអាសយដ្ឋាន IPv4", "MAC Address Formatter": "រៀបចំទម្រង់អាសយដ្ឋាន MAC", "HTTP Status Code Reference": "តារាងកូដស្ថានភាព HTTP", "User-Agent String Parser": "វិភាគខ្សែអក្សរ User-Agent", "URL Parser & Query String Inspector": "វិភាគ URL និងពិនិត្យ Query String", "DNS Record Type Reference": "តារាងប្រភេទកំណត់ត្រា DNS", "HTML Entity Encoder / Decoder": "អ៊ិនកូដ / ឌិកូដ HTML Entity", "Common Port Number Reference": "តារាងលេខ Port ទូទៅ", "MIME Type Lookup": "ស្វែងរកប្រភេទ MIME", "Domain / Slug Validity Checker": "ពិនិត្យសុពលភាព Domain / Slug", "IPv6 Address Compressor / Expander": "បង្រួម / ពង្រីកអាសយដ្ឋាន IPv6", "Random Private IP Generator": "បង្កើត IP ឯកជនចៃដន្យ",
  // Security
  "ROT13 / Caesar Cipher": "ស៊ីហ្វ័រ ROT13 / Caesar", "Base32 Encode / Decode": "អ៊ិនកូដ / ឌិកូដ Base32", "Hex Dump Viewer": "មើលទិន្នន័យ Hex Dump", "Random PIN Generator": "បង្កើតលេខ PIN ចៃដន្យ", "Namespace UUID (v5) Generator": "បង្កើត Namespace UUID (v5)", "JWT Encoder (HS256)": "អ៊ិនកូដ JWT (HS256)", "Luhn Algorithm Card Validator": "ផ្ទៀងផ្ទាត់លេខកាតដោយក្បួន Luhn", "Vigenère Cipher": "ស៊ីហ្វ័រ Vigenère", "Random Bytes / Key Generator": "បង្កើតបៃ / សោចៃដន្យ", "Passphrase Generator": "បង្កើតឃ្លាសម្ងាត់", "Credit Card Number Masker": "បិទបាំងលេខប័ណ្ណឥណទាន",
  // Design
  "Favicon Generator": "បង្កើត Favicon", "Iconsmith": "Iconsmith", "Auth Architecture Lab": "មគ្គុទ្ទេសក៍ស្ថាបត្យកម្មប្រព័ន្ធសន្តិសុខ និងការផ្ទៀងផ្ទាត់", "Khmer Loanword Explorer": "កម្មវិធីស្រាវជ្រាវពាក្យកម្ចីក្នុងភាសាខ្មែរ", "Khmer Sentence Builder": "ល្បែងផ្គុំល្បះខ្មែរ", "Chhmoh Astrology Portal": "ឈ្មោះ ហោរាសាស្ត្រខ្មែរ",   "Homophone": "សទិសសូរ", "Khmer Root & Word Formation Explorer": "អ្នករុករកឫសគល់ពាក្យខ្មែរ", "Decimen Optical Transfer": "ដេស៊ីម៉ិន បញ្ជូនឯកសារតាមពន្លឺ", "IPC Proportion Calculator": "ម៉ាស៊ីនគណនាសមាមាត្រ IPC", "WebRTC File Transfer": "បញ្ជូនឯកសារ WebRTC", "Cambodia Fuel Prices": "តម្លៃប្រេងឥន្ធនៈកម្ពុជា", "API Benchmark": "ប្រៀបធៀបល្បឿន API", "JSON → TypeScript / Zod": "បម្លែង JSON → TypeScript / Zod", "JSON Data Converter": "កម្មវិធីបម្លែងទិន្នន័យ JSON", "JSONL Validator": "ផ្ទៀងផ្ទាត់ JSONL", "AI Token Counter": "រាប់ Token AI", "123 Smart Input": "ការបញ្ចូលឆ្លាតវៃ ១២៣", "Tool Chains": "ខ្សែសង្វាក់ឧបករណ៍",   "Khmer Name Structure Explorer": "កម្មវិធីវិភាគរចនាសម្ព័ន្ធឈ្មោះខ្មែរ", "Yellow Card Tracker": "ប័ណ្ណសុខភាពកុមារជាតិ", "Data Residency Map": "ផែនទីទីតាំងទិន្នន័យ", "Social Preview (OG) Image Generator": "បង្កើតរូបភាពមើលជាមុនបណ្ដាញសង្គម (OG)", "Color Palette Generator": "បង្កើតក្ដារលាយពណ៌", "WCAG Contrast Checker": "ពិនិត្យកម្រិតផ្ទុយពណ៌ WCAG", "CSS Gradient Generator": "បង្កើតជម្រាលពណ៌ CSS", "Box Shadow Generator": "បង្កើតស្រមោលប្រអប់", "Border Radius Previewer": "មើលកាំជ្រុងជាមុន", "CSS Unit Converter": "បម្លែងឯកតា CSS", "Aspect Ratio Calculator": "គណនាសមាមាត្ររូបភាព", "Spacing Scale Generator": "បង្កើតមាត្រដ្ឋានគម្លាត", "Tints & Shades Generator": "បង្កើតពណ៌ស្រាល និងពណ៌ងងឹត", "CSS clamp() Calculator": "គណនា CSS clamp()", "Favicon & App Icon Size Reference": "តារាងទំហំ Favicon និងរូបតំណាងកម្មវិធី", "Golden Ratio Calculator": "គណនាសមាមាត្រមាស", "Nearest CSS Color Name Finder": "ស្វែងរកឈ្មោះពណ៌ CSS ជិតបំផុត", "VectorDrawable → SVG": "បម្លែង VectorDrawable → SVG",
  // Time and date
  "Age Calculator": "គណនាអាយុ", "Date Difference Calculator": "គណនាគម្លាតកាលបរិច្ឆេទ", "Countdown Timer": "កម្មវិធីរាប់ថយក្រោយ", "Timezone Converter": "បម្លែងតំបន់ពេលវេលា", "ISO Week Number Calculator": "គណនាលេខសប្ដាហ៍ ISO", "Business Days Calculator": "គណនាថ្ងៃធ្វើការ", "Stopwatch": "នាឡិកាកំណត់ពេល", "Pomodoro Timer": "កម្មវិធីកំណត់ពេល Pomodoro", "Relative Time (\"Time Ago\") Formatter": "រៀបចំពេលវេលាធៀប (ពេលមុន)", "Calendar Month Generator": "បង្កើតប្រតិទិនប្រចាំខែ", "Moon Phase Calculator": "គណនាដំណាក់កាលព្រះចន្ទ", "Duration Adder / Subtractor": "បូក / ដករយៈពេល", "Shift Duration Calculator": "គណនារយៈពេលវេនការងារ",
  // Office
  "Currency Amount to Words": "សរសេរចំនួនទឹកប្រាក់ជាពាក្យ", "Document / Invoice Number Generator": "បង្កើតលេខឯកសារ / វិក្កយបត្រ", "PDF Info & Preview": "ព័ត៌មាន និងមើល PDF ជាមុន", "PDF Merge": "បញ្ចូល PDF ចូលគ្នា", "PDF Page Organizer": "រៀបចំទំព័រ PDF", "File Compressor": "បង្រួមទំហំឯកសារ", "PDF Watermark": "ដាក់ Watermark លើ PDF", "Images → PDF": "បម្លែងរូបភាព → PDF", "PDF → Images": "បម្លែង PDF → រូបភាព", "QR Code Decoder": "អានកូដ QR", "QR Code Generator": "បង្កើតកូដ QR", "Expense Tracker": "កត់ត្រាចំណាយ",
  // Images, audio, and video
  "Image Watermark": "ដាក់ Watermark លើរូបភាព", "Logo / Watermark Remover": "លុប Logo / Watermark", "Image Metadata (EXIF) Viewer & Stripper": "មើល និងលុបទិន្នន័យមេតារូបភាព (EXIF)", "Image ⇄ Base64 Converter": "បម្លែងរូបភាព ⇄ Base64", "Audio Editor": "កម្មវិធីកែសំឡេង", "Audio File Inspector": "ពិនិត្យឯកសារសំឡេង", "Video Thumbnail Grabber": "ទាញយករូបភាពតូចពីវីដេអូ", "Video Trimmer": "កាត់តវីដេអូ", "Video → GIF": "បម្លែងវីដេអូ → GIF", "Video File Inspector": "ពិនិត្យឯកសារវីដេអូ"
});
const UNITS: Record<string, string> = {
  meter: "ម៉ែត្រ", kilometer: "គីឡូម៉ែត្រ", centimeter: "សង់ទីម៉ែត្រ", millimeter: "មីលីម៉ែត្រ", mile: "ម៉ាយល៍", yard: "យ៉ាត", foot: "ហ្វីត", inch: "អ៊ីញ",
  kilogram: "គីឡូក្រាម", gram: "ក្រាម", milligram: "មីលីក្រាម", pound: "ផោន", ounce: "អោន", "metric ton": "តោនម៉ែត្រ", stone: "ស្តូន",
  liter: "លីត្រ", milliliter: "មីលីលីត្រ", "cubic meter": "ម៉ែត្រគូប", gallon: "ហ្គាឡុង", quart: "ក្វាត", pint: "ផៃន៍", cup: "ពែង", "fluid ounce": "អោនរាវ",
  "square meter": "ម៉ែត្រការ៉េ", "square kilometer": "គីឡូម៉ែត្រការ៉េ", hectare: "ហិកតា", "square foot": "ហ្វីតការ៉េ", "square yard": "យ៉ាតការ៉េ", acre: "អេក", "square mile": "ម៉ាយល៍ការ៉េ",
  "meter/second": "ម៉ែត្រ/វិនាទី", "kilometer/hour": "គីឡូម៉ែត្រ/ម៉ោង", "mile/hour": "ម៉ាយល៍/ម៉ោង", knot: "ណត", "foot/second": "ហ្វីត/វិនាទី",
  pascal: "ប៉ាស្កាល់", kilopascal: "គីឡូប៉ាស្កាល់", bar: "បារ", psi: "PSI", atmosphere: "អាតម៉ូស្វ៊ែរ", torr: "ត័រ",
  joule: "ជូល", kilojoule: "គីឡូជូល", calorie: "កាឡូរី", kilocalorie: "គីឡូកាឡូរី", "watt-hour": "វ៉ាត់-ម៉ោង", "kilowatt-hour": "គីឡូវ៉ាត់-ម៉ោង", btu: "BTU",
  watt: "វ៉ាត់", kilowatt: "គីឡូវ៉ាត់", horsepower: "កម្លាំងសេះ", "btu/hour": "BTU/ម៉ោង",
  byte: "បៃ", kilobyte: "គីឡូបៃ", megabyte: "មេហ្គាបៃ", gigabyte: "ជីហ្គាបៃ", terabyte: "តេរ៉ាបៃ", bit: "ប៊ីត", kibibyte: "គីប៊ីបៃ", mebibyte: "មេប៊ីបៃ",
  second: "វិនាទី", minute: "នាទី", hour: "ម៉ោង", day: "ថ្ងៃ", week: "សប្តាហ៍", year: "ឆ្នាំ", celsius: "សែលស្យុស", fahrenheit: "ហ្វារិនហៃ", kelvin: "កែលវិន"
};
const PARTS: [string, string][] = [
  ["Government Institution Directory", "បញ្ជីស្ថាប័នរាជរដ្ឋាភិបាល"], ["Administrative Hierarchy", "ឋានានុក្រមរដ្ឋបាល"], ["Postal Code Finder", "ស្វែងរកលេខកូដប្រៃសណីយ៍"], ["Government Plate Lookup", "ស្វែងរកស្លាកលេខរដ្ឋ"],
  ["Generator", "ឧបករណ៍បង្កើត"], ["Converter", "ឧបករណ៍បម្លែង"], ["Calculator", "ម៉ាស៊ីនគណនា"], ["Formatter", "ឧបករណ៍រៀបចំទម្រង់"], ["Checker", "ឧបករណ៍ត្រួតពិនិត្យ"], ["Validator", "ឧបករណ៍ផ្ទៀងផ្ទាត់"], ["Reference", "ឯកសារយោង"], ["Directory", "បញ្ជី"], ["Inspector", "ឧបករណ៍ត្រួតពិនិត្យ"], ["Viewer", "កម្មវិធីមើល"], ["Editor", "កម្មវិធីកែសម្រួល"],
  ["Encoder", "ឧបករណ៍អ៊ិនកូដ"], ["Decoder", "ឧបករណ៍ឌីកូដ"], ["Parser", "ឧបករណ៍វិភាគ"], ["Finder", "ឧបករណ៍ស្វែងរក"], ["Counter", "ឧបករណ៍រាប់"], ["Remover", "ឧបករណ៍លុប"], ["Optimizer", "ឧបករណ៍បង្កើនប្រសិទ្ធភាព"], ["Previewer", "កម្មវិធីមើលជាមុន"],
  ["Image", "រូបភាព"], ["Text", "អត្ថបទ"], ["Color", "ពណ៌"], ["Date", "កាលបរិច្ឆេទ"], ["Time", "ពេលវេលា"], ["Number", "លេខ"], ["File", "ឯកសារ"], ["PDF", "PDF"], ["Khmer", "ខ្មែរ"], ["Cambodia", "កម្ពុជា"],
];
function unit(value: string) { return UNITS[value.trim().toLowerCase()] ?? value.trim(); }
export function toKhmerToolTitle(title: string) {
  if (EXACT[title]) return EXACT[title];
  if (title.includes("⟷")) { const [a, b] = title.split("⟷"); return `${unit(a)} ⟷ ${unit(b)}`; }
  let translated = title;
  for (const [en, km] of PARTS) translated = translated.replaceAll(en, km);
  return translated === title ? `ឧបករណ៍ ${title}` : translated;
}
