export interface WordBankEntry {
  text: string;
  clue: string;
}

export interface WordBank {
  id: string;
  label: string;
  entries: WordBankEntry[];
}

export const WORD_BANKS: WordBank[] = [
  {
    id: "animals",
    label: "Animals",
    entries: [
      { text: "ឆ្កែ", clue: "Dog" },
      { text: "ឆ្មា", clue: "Cat" },
      { text: "ត្រី", clue: "Fish" },
      { text: "ស្វា", clue: "Monkey" },
      { text: "មាន់", clue: "Chicken" },
      { text: "គោ", clue: "Cow" },
      { text: "ដំរី", clue: "Elephant" },
      { text: "កង្កែប", clue: "Frog" },
      { text: "សេះ", clue: "Horse" },
      { text: "ជ្រូក", clue: "Pig" },
      { text: "ខ្លា", clue: "Tiger" },
      { text: "សិង្ហ", clue: "Lion" },
      { text: "ក្របី", clue: "Water buffalo" },
      { text: "ទា", clue: "Duck" },
      { text: "ពស់", clue: "Snake" },
      { text: "ខ្លាឃ្មុំ", clue: "Bear" },
      { text: "ទន្សាយ", clue: "Rabbit" },
      { text: "បក្សី", clue: "Bird" },
      { text: "តោ", clue: "Lion" },
      { text: "ក្តាន់", clue: "Deer" },
      { text: "កណ្តុរ", clue: "Mouse" },
      { text: "អណ្តើក", clue: "Turtle" },
      { text: "ក្រពើ", clue: "Crocodile" },
      { text: "ពពែ", clue: "Goat" },
      { text: "ចៀម", clue: "Sheep" },
      { text: "ពីងពាង", clue: "Spider" },
      { text: "ស្រមោច", clue: "Ant" },
      { text: "ឃ្មុំ", clue: "Bee" },
      { text: "មេអំបៅ", clue: "Butterfly" },
      { text: "មូស", clue: "Mosquito" },
      { text: "រុយ", clue: "Fly" },
      { text: "ក្តាម", clue: "Crab" },
      { text: "បង្គា", clue: "Shrimp" },
      { text: "មឹក", clue: "Squid" },
      { text: "ត្រីឆ្លាម", clue: "Shark" },
      { text: "បាឡែន", clue: "Whale" },
      { text: "ផ្សោត", clue: "Dolphin" },
    ],
  },
  {
    id: "colors",
    label: "Colors",
    entries: [
      { text: "ក្រហម", clue: "Red" },
      { text: "លឿង", clue: "Yellow" },
      { text: "ខៀវ", clue: "Blue" },
      { text: "បៃតង", clue: "Green" },
      { text: "ស", clue: "White" },
      { text: "ខ្មៅ", clue: "Black" },
      { text: "ទឹកក្រូច", clue: "Orange" },
      { text: "ស្វាយ", clue: "Purple" },
      { text: "ត្នោត", clue: "Brown" },
      { text: "ប្រផេះ", clue: "Gray" },
    ],
  },
  {
    id: "numbers",
    label: "Numbers 1–10",
    entries: [
      { text: "មួយ", clue: "One" },
      { text: "ពីរ", clue: "Two" },
      { text: "បី", clue: "Three" },
      { text: "បួន", clue: "Four" },
      { text: "ប្រាំ", clue: "Five" },
      { text: "ប្រាំមួយ", clue: "Six" },
      { text: "ប្រាំពីរ", clue: "Seven" },
      { text: "ប្រាំបី", clue: "Eight" },
      { text: "ប្រាំបួន", clue: "Nine" },
      { text: "ដប់", clue: "Ten" },
    ],
  },
  {
    id: "family",
    label: "Family",
    entries: [
      { text: "ឪពុក", clue: "Father" },
      { text: "ម្តាយ", clue: "Mother" },
      { text: "បង", clue: "Older sibling" },
      { text: "ប្អូន", clue: "Younger sibling" },
      { text: "កូន", clue: "Child" },
      { text: "ជីតា", clue: "Grandfather" },
      { text: "ជីដូន", clue: "Grandmother" },
      { text: "ប្រពន្ធ", clue: "Wife" },
      { text: "ប្តី", clue: "Husband" },
      { text: "ចៅ", clue: "Grandchild" },
      { text: "មីង", clue: "Aunt" },
      { text: "ពូ", clue: "Uncle" },
    ],
  },
  {
    id: "food",
    label: "Food",
    entries: [
      { text: "បាយ", clue: "Rice" },
      { text: "សាច់", clue: "Meat" },
      { text: "បន្លែ", clue: "Vegetable" },
      { text: "ផ្លែឈើ", clue: "Fruit" },
      { text: "ទឹក", clue: "Water" },
      { text: "នំបុ័ង", clue: "Bread" },
      { text: "ស្ករ", clue: "Sugar" },
      { text: "អំបិល", clue: "Salt" },
      { text: "ម្ទេស", clue: "Chili" },
      { text: "ខ្ទឹមស", clue: "Garlic" },
      { text: "ស៊ុប", clue: "Soup" },
    ],
  },
  {
    id: "school",
    label: "School",
    entries: [
      { text: "សៀវភៅ", clue: "Book" },
      { text: "ខ្មៅដៃ", clue: "Pencil" },
      { text: "ក្រដាស", clue: "Paper" },
      { text: "គ្រូ", clue: "Teacher" },
      { text: "សិស្ស", clue: "Student" },
      { text: "តុ", clue: "Table" },
      { text: "កៅអី", clue: "Chair" },
      { text: "ប៊ិក", clue: "Pen" },
      { text: "ក្តារខៀន", clue: "Blackboard" },
    ],
  },
  {
    id: "provinces",
    label: "Cambodian provinces",
    entries: [
      { text: "ភ្នំពេញ", clue: "Capital city, on the Mekong" },
      { text: "កំពង់ចាម", clue: "Province, an old French bridge town" },
      { text: "កំពង់ធំ", clue: 'Province whose name means "big port"' },
      { text: "កំពង់ស្ពឺ", clue: "Province between the capital and the coast" },
      { text: "កំពត", clue: "Province famous for its pepper" },
      { text: "សៀមរាប", clue: "Gateway to Angkor" },
      { text: "តាកែវ", clue: "Province south of the capital" },
      { text: "ស្វាយរៀង", clue: "Border province toward Vietnam" },
      { text: "បាត់ដំបង", clue: "Rice bowl of Cambodia" },
      { text: "ព្រះសីហនុ", clue: "Cambodia's main coastal city" },
      { text: "ភ្នំ", clue: 'Word for "mountain"' },
    ],
  },
  {
    id: "fruits",
    label: "Fruits",
    entries: [
      { text: "ចេក", clue: "Banana" },
      { text: "ស្វាយ", clue: "Mango" },
      { text: "ម្នាស់", clue: "Pineapple" },
      { text: "ផ្លែប៉ោម", clue: "Apple" },
      { text: "ឪឡឹក", clue: "Watermelon" },
      { text: "ក្រូច", clue: "Orange" },
      { text: "ទំពាំងបាយជូរ", clue: "Grape" },
      { text: "ដូង", clue: "Coconut" },
      { text: "ល្ហុង", clue: "Papaya" },
      { text: "ខ្នុរ", clue: "Jackfruit" },
      { text: "ទុរេន", clue: "Durian" },
      { text: "សាវម៉ាវ", clue: "Rambutan" },
      { text: "មង្ឃុត", clue: "Mangosteen" },
      { text: "ស្រកានាគ", clue: "Dragon fruit" },
      { text: "ត្របែក", clue: "Guava" },
      { text: "ក្រូចឆ្មារ", clue: "Lemon" },
      { text: "ស្ត្របឺរី", clue: "Strawberry" },
      { text: "ផ្លែបឺរ", clue: "Avocado" },
      { text: "ទទឹម", clue: "Pomegranate" },
      { text: "គូលែន", clue: "Lychee" },
      { text: "មៀន", clue: "Longan" },
    ],
  },
  {
    id: "vegetables",
    label: "Vegetables",
    entries: [
      { text: "ការ៉ុត", clue: "Carrot" },
      { text: "ដំឡូង", clue: "Potato" },
      { text: "ប៉េងប៉ោះ", clue: "Tomato" },
      { text: "ខ្ទឹមបារាំង", clue: "Onion" },
      { text: "ខ្ទឹមស", clue: "Garlic" },
      { text: "ស្ពៃក្តោប", clue: "Cabbage" },
      { text: "ត្រប់", clue: "Eggplant" },
      { text: "ត្រសក់", clue: "Cucumber" },
      { text: "ល្ពៅ", clue: "Pumpkin" },
      { text: "ម្ទេស", clue: "Chili" },
      { text: "ខ្ញី", clue: "Ginger" },
      { text: "ផ្សិត", clue: "Mushroom" },
      { text: "ពោត", clue: "Corn" },
      { text: "សណ្តែក", clue: "Bean" },
      { text: "សាឡាត់", clue: "Lettuce" },
      { text: "ខាត់ណា", clue: "Broccoli" },
      { text: "ស្ពៃខ្មៅ", clue: "Spinach" },
    ],
  },
  {
    id: "nature",
    label: "Nature",
    entries: [
      { text: "ព្រះអាទិត្យ", clue: "Sun" },
      { text: "ព្រះច័ន្ទ", clue: "Moon" },
      { text: "ផ្កាយ", clue: "Star" },
      { text: "មេឃ", clue: "Sky" },
      { text: "ពពក", clue: "Cloud" },
      { text: "ភ្លៀង", clue: "Rain" },
      { text: "ខ្យល់", clue: "Wind" },
      { text: "ព្រិល", clue: "Snow" },
      { text: "ភ្នំ", clue: "Mountain" },
      { text: "ទន្លេ", clue: "River" },
      { text: "បឹង", clue: "Lake" },
      { text: "សមុទ្រ", clue: "Ocean" },
      { text: "ដើមឈើ", clue: "Tree" },
      { text: "ផ្កា", clue: "Flower" },
      { text: "ស្មៅ", clue: "Grass" },
      { text: "ស្លឹក", clue: "Leaf" },
      { text: "ដី", clue: "Earth / Dirt" },
      { text: "ថ្ម", clue: "Rock" },
      { text: "ភ្លើង", clue: "Fire" },
      { text: "ខ្សាច់", clue: "Sand" },
      { text: "ព្រៃ", clue: "Forest" },
    ],
  },
  {
    id: "body",
    label: "Body parts",
    entries: [
      { text: "ក្បាល", clue: "Head" },
      { text: "សក់", clue: "Hair" },
      { text: "ភ្នែក", clue: "Eye" },
      { text: "ត្រចៀក", clue: "Ear" },
      { text: "ច្រមុះ", clue: "Nose" },
      { text: "មាត់", clue: "Mouth" },
      { text: "ធ្មេញ", clue: "Tooth" },
      { text: "អណ្តាត", clue: "Tongue" },
      { text: "មុខ", clue: "Face" },
      { text: "ក", clue: "Neck" },
      { text: "ស្មា", clue: "Shoulder" },
      { text: "ដៃ", clue: "Arm" },
      { text: "បាតដៃ", clue: "Hand" },
      { text: "ម្រាមដៃ", clue: "Finger" },
      { text: "ទ្រូង", clue: "Chest" },
      { text: "ពោះ", clue: "Stomach" },
      { text: "ខ្នង", clue: "Back" },
      { text: "ជើង", clue: "Leg" },
      { text: "បាតជើង", clue: "Foot" },
      { text: "ម្រាមជើង", clue: "Toe" },
      { text: "បេះដូង", clue: "Heart" },
      { text: "ឈាម", clue: "Blood" },
      { text: "ស្បែក", clue: "Skin" },
      { text: "ឆ្អឹង", clue: "Bone" },
    ],
  },
  {
    id: "professions",
    label: "Professions",
    entries: [
      { text: "គ្រូពេទ្យ", clue: "Doctor" },
      { text: "គ្រូបង្រៀន", clue: "Teacher" },
      { text: "សិស្ស", clue: "Student" },
      { text: "ប៉ូលីស", clue: "Police" },
      { text: "ទាហាន", clue: "Soldier" },
      { text: "កសិករ", clue: "Farmer" },
      { text: "កម្មករ", clue: "Worker" },
      { text: "អ្នកបើកបរ", clue: "Driver" },
      { text: "ចុងភៅ", clue: "Cook" },
      { text: "អ្នកចម្រៀង", clue: "Singer" },
      { text: "តារាសម្តែង", clue: "Actor" },
      { text: "អ្នកនិពន្ធ", clue: "Writer" },
      { text: "វិស្វករ", clue: "Engineer" },
      { text: "អ្នកលក់", clue: "Seller" },
    ],
  },
  {
    id: "places",
    label: "Places",
    entries: [
      { text: "សាលារៀន", clue: "School" },
      { text: "មន្ទីរពេទ្យ", clue: "Hospital" },
      { text: "ផ្សារ", clue: "Market" },
      { text: "ធនាគារ", clue: "Bank" },
      { text: "សណ្ឋាគារ", clue: "Hotel" },
      { text: "ភោជនីយដ្ឋាន", clue: "Restaurant" },
      { text: "អាកាសយានដ្ឋាន", clue: "Airport" },
      { text: "ស្ថានីយ៍", clue: "Station" },
      { text: "វត្ត", clue: "Temple" },
      { text: "ព្រះវិហារ", clue: "Church" },
      { text: "ការិយាល័យ", clue: "Office" },
      { text: "ផ្ទះ", clue: "House" },
      { text: "ភូមិ", clue: "Village" },
      { text: "ទីក្រុង", clue: "City" },
      { text: "ប្រទេស", clue: "Country" },
    ],
  },
  {
    id: "time",
    label: "Time & days",
    entries: [
      { text: "ច័ន្ទ", clue: "Monday" },
      { text: "អង្គារ", clue: "Tuesday" },
      { text: "ពុធ", clue: "Wednesday" },
      { text: "ព្រហស្បតិ៍", clue: "Thursday" },
      { text: "សុក្រ", clue: "Friday" },
      { text: "សៅរ៍", clue: "Saturday" },
      { text: "អាទិត្យ", clue: "Sunday" },
      { text: "ថ្ងៃ", clue: "Day" },
      { text: "យប់", clue: "Night" },
      { text: "ព្រឹក", clue: "Morning" },
      { text: "រសៀល", clue: "Afternoon" },
      { text: "ល្ងាច", clue: "Evening" },
      { text: "សប្តាហ៍", clue: "Week" },
      { text: "ខែ", clue: "Month" },
      { text: "ឆ្នាំ", clue: "Year" },
      { text: "ថ្ងៃនេះ", clue: "Today" },
      { text: "ថ្ងៃស្អែក", clue: "Tomorrow" },
      { text: "ម្សិលមិញ", clue: "Yesterday" },
    ],
  },
  {
    id: "actions",
    label: "Actions / verbs",
    entries: [
      { text: "ទៅ", clue: "Go" },
      { text: "មក", clue: "Come" },
      { text: "ញ៉ាំ", clue: "Eat" },
      { text: "ផឹក", clue: "Drink" },
      { text: "ដេក", clue: "Sleep" },
      { text: "រត់", clue: "Run" },
      { text: "ដើរ", clue: "Walk" },
      { text: "លោត", clue: "Jump" },
      { text: "និយាយ", clue: "Speak" },
      { text: "ស្តាប់", clue: "Listen" },
      { text: "អាន", clue: "Read" },
      { text: "សរសេរ", clue: "Write" },
      { text: "មើល", clue: "See" },
      { text: "គិត", clue: "Think" },
      { text: "ដឹង", clue: "Know" },
      { text: "ធ្វើការ", clue: "Work" },
      { text: "លេង", clue: "Play" },
      { text: "ទិញ", clue: "Buy" },
      { text: "លក់", clue: "Sell" },
      { text: "ស្រឡាញ់", clue: "Love" },
      { text: "ញញឹម", clue: "Smile" },
      { text: "សើច", clue: "Laugh" },
      { text: "យំ", clue: "Cry" },
    ],
  },
];
